- name: Ensure that nginx is installed
  apt: name=nginx state=present
  when: ansible_os_family == 'Debian'

- name: Deploy nginx basic config
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf

- name: Deploy nginx site config
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  notify: 
  - Restart nginx

- name: Ensure nginx is running
  service: name=nginx enabled=yes state=started

- name: Copy files
  template: src=index.j2 dest={{ doc_root }}/index.html
